### ISSUE TITLE
Will not build on Heroku with Node 0.12.2

### ISSUE THREAD

**Issue by thanpolas** [mscdex/mmmagic#49]
I'll give it a stuv here, although I have successfully manage to build mmmagic on my local 0.12.2 node environment, it isn't the case when deploying to Heroku.

While installing the following compile errors occurred:

```
       ../deps/libmagic/src/cdf.c: In function 'cdf_read':
       ../deps/libmagic/src/cdf.c:303:2: warning: implicit declaration of function 'pread' [-Wimplicit-function-declaration]
         if (pread(info->i_fd, buf, len, off) != (ssize_t)len)

         CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_compile.o
       ../deps/libmagic/pcre/pcre_compile.c: In function 'add_to_class':
       ../deps/libmagic/pcre/pcre_compile.c:3487:30: warning: 'od' may be used uninitialized in this function [-Wmaybe-uninitialized]
              else n8 += add_to_class(classbits, uchardptr, options, cd, oc, od);
                           

         COPY Release/pcre.a
         CXX(target) Release/obj.target/magic/src/magic.o
       ../src/magic.cc:18:5: error: 'uv_work_t' does not name a type
            uv_work_t request;
            ^
       ../src/magic.cc:39:33: error: expected class-name before '{' token
        class Magic : public ObjectWrap {
                                        ^

```

The full install logs [can be found in this gist](https://gist.github.com/thanpolas/e5ee64bdc18c7e436aa4).

**Comment by mscdex** [comment]
Can you try installing the master branch instead of mmmagic 0.3.12? If that works, I will publish a new version.

**Comment by thanpolas** [comment]
yes 0.3.13 worked! Thank you @mscdex
