### ISSUE TITLE
Cannot build on node v0.11.13 / Gentoo linux 3.12.21-r1

### ISSUE THREAD

**Issue by mblasi** [mscdex/mmmagic#29]
Hi, I'm getting the following error when trying to build mmmagic:

/home/matias/.node-gyp/0.11.13/deps/v8/include/v8.h:5757:4: note:   candidate expects 2 arguments, 1 provided
../src/magic.cc:286:18: error: base operand of ‘->’ has non-pointer type ‘v8::Persistentv8::FunctionTemplate’
../src/magic.cc:287:18: error: base operand of ‘->’ has non-pointer type ‘v8::Persistentv8::FunctionTemplate’
../src/magic.cc:289:70: error: could not convert ‘constructor’ from ‘v8::Persistentv8::FunctionTemplate’ to ‘v8::Handlev8::FunctionTemplate’
../src/magic.cc:290:62: error: could not convert ‘constructor’ from ‘v8::Persistentv8::FunctionTemplate’ to ‘v8::Handlev8::FunctionTemplate’
../src/magic.cc:291:19: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/magic.cc:292:42: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handlev8::Value (&)(const int&))’
../src/magic.cc:292:42: note: candidate is:
In file included from /home/matias/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/magic.cc:1:
/home/matias/.node-gyp/0.11.13/deps/v8/include/v8.h:3519:34: note: static v8::Localv8::FunctionTemplate v8::FunctionTemplate::New(v8::Isolate_, v8::FunctionCallback, v8::Handlev8::Value, v8::Handlev8::Signature, int)
/home/matias/.node-gyp/0.11.13/deps/v8/include/v8.h:3519:34: note:   no known conversion for argument 1 from ‘v8::Handlev8::Value(const int&)’ to ‘v8::Isolate_’
../src/magic.cc:294:36: error: base operand of ‘->’ has non-pointer type ‘v8::Persistentv8::FunctionTemplate’
In file included from /home/matias/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/magic.cc:1:
/home/matias/.node-gyp/0.11.13/deps/v8/include/v8.h: In function ‘void init(v8::Handlev8::Object)’:
/home/matias/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/magic.cc:300:17: error: within this context
make: **\* [Release/obj.target/magic/src/magic.o] Error 1
make: Leaving directory `/home/matias/workspaces/scool/node_modules/mmmagic/build'
gyp ERR! build error 
gyp ERR! stack Error:`make`failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.12.21-gentoo-r1
gyp ERR! command "node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/matias/workspaces/scool/node_modules/mmmagic
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! mmmagic@0.3.8 install:`node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmmagic@0.3.8 install script.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.21-gentoo-r1
npm ERR! command "node" "/usr/bin/npm" "install" "mmmagic"
npm ERR! cwd /home/matias/workspaces/scool
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/matias/workspaces/scool/npm-debug.log
npm ERR! not ok code 0
