### ISSUE TITLE
doesn't compile on node 0.9.4

### ISSUE THREAD

**Issue by dready92** [mscdex/mmmagic#7]
Hello,

it seems mmmagic doesn't compile anymore using node-0.9.4 ...

Here is the error:

```
../src/magic.cc:131:71: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/mickael/.node-gyp/0.9.4/src/node.h:61:0,
             from ../src/magic.cc:1:
/home/mickael/.node-gyp/0.9.4/deps/uv/include/uv.h:1386:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/magic.cc: In static member function ‘static v8::Handle<v8::Value> Magic::Detect(const v8::Arguments&)’:
../src/magic.cc:169:71: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/mickael/.node-gyp/0.9.4/src/node.h:61:0,
             from ../src/magic.cc:1:
/home/mickael/.node-gyp/0.9.4/deps/uv/include/uv.h:1386:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
make: *** [Release/obj.target/magic/src/magic.o] Error 1
make: Leaving directory `/home/mickael/d10/node_modules/mmmagic/build
```

Can you have a look ?

Thanks'
