### ISSUE TITLE
issue building with Node.JS 0.10.0

### ISSUE THREAD

**Issue by jokeyrhyme** [mscdex/mmmagic#9]
After updating to 0.10.0, I tried running my Node program that uses mmmagic and I got the following:

```
module.js:340
    throw err;
          ^
Error: Cannot find module './build/Release/magic'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/bignslow/Projects/cdn-sync/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I then tried to do a `npm rebuild` with the following results:
https://gist.github.com/jokeyrhyme/5137321

I'm pretty poor at C and C++, but I'm guessing something along the JS-C++ bridge changed with the latest Node.JS. /shrug

Let me know if I can help further.
